name: CI/CD
on:
  pull_request:
    types:
      - "ready_for_review"
    branches:
      - 'master'
      - 'staging'
      - 'production'
jobs:
  codeql:
    name: Execute CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
